-- MySQL Script generated by MySQL Workbench
-- 11/01/15 12:15:31
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Languages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Languages` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Name` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Words`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Words` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `Word` VARCHAR(45) NOT NULL,
  `Meaning` INT NULL,
  `Language` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Words_Words_idx` (`Meaning` ASC),
  INDEX `fk_Words_Languages1_idx` (`Language` ASC),
  CONSTRAINT `fk_Words_Words`
    FOREIGN KEY (`Meaning`)
    REFERENCES `mydb`.`Words` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Words_Languages1`
    FOREIGN KEY (`Language`)
    REFERENCES `mydb`.`Languages` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
